export interface NBCOption {
  value: string;
  label: string;
  points: number;
}

export interface Selections {
  firstName: string;
  lastName: string;
  company: string;
  companyAddress: string;
  buildingAddress: string;
  buildingType: string;
  phoneNumber: string;
  frontDoorOrientation: string;
  province: string;
  climateZone: string;
  occupancyClass: string;
  compliancePath: string;
  isVolumeOver380: string;
  buildingVolume: string;
  ceilingsAtticRSI: string;
  ceilingsAtticOtherType: string;
  hasCathedralOrFlatRoof: string;
  cathedralFlatRSI: string;
  cathedralFlatRSIValue: string;
  cathedralFlatOtherType: string;
  wallRSI: string;
  floorsUnheatedRSI: string;
  floorsGarageRSI: string;
  hasSkylights: string;
  skylightUValue: string;
  hasSlabOnGrade: string;
  hasSlabIntegralFooting: string;
  slabInsulation: string;
  slabInsulationValue: string;
  hasInFloorHeat: string;
  hasInFloorHeat9365: string;
  floorsSlabsSelected: string[];
  inFloorHeatRSI: string;
  foundationWallsRSI: string;
  slabOnGradeRSI: string;
  slabOnGradeIntegralFootingRSI: string;
  floorsOverUnheatedSpacesRSI: string;
  unheatedFloorBelowFrostRSI: string;
  unheatedFloorAboveFrostRSI: string;
  heatedFloorsRSI: string;
  windowUValue: string;
  belowGradeRSI: string;
  airtightness: string;
  customAirtightness: string;
  atticRSI: string;
  hasHrv: string;
  hrv: string;
  hasHrvErv9365: string;
  hrvMakeModel: string;
  hrvEfficiency: string;
  hasSecondaryHrv: string;
  secondaryHrvEfficiency: string;
  waterHeater: string;
  waterHeaterMakeModel: string;
  waterHeaterType: string;
  otherWaterHeaterType: string;
  hasSecondaryWaterHeater: string;
  secondaryWaterHeaterSameAsMain: string;
  secondaryWaterHeater: string;
  secondaryWaterHeaterType: string;
  hasMurbMultipleWaterHeaters: string;
  murbSecondWaterHeater: string;
  murbSecondWaterHeaterType: string;
  hasDWHR: string;
  heatingType: string;
  heatingMakeModel: string;
  heatingEfficiency: string;
  hasSecondaryHeating: string;
  secondaryHeatingType: string;
  secondaryHeatingEfficiency: string;
  secondaryIndirectTank: string;
  secondaryIndirectTankSize: string;
  hasMurbMultipleHeating: string;
  murbSecondHeatingType: string;
  murbSecondHeatingEfficiency: string;
  murbSecondIndirectTank: string;
  murbSecondIndirectTankSize: string;
  indirectTank: string;
  indirectTankSize: string;
  coolingApplicable: string;
  coolingEfficiency: string;
  coolingMakeModel: string;
  hasF280Calculation: string;
  additionalInfo: string;
  interestedCertifications: string[];
  midConstructionBlowerDoorPlanned: boolean;
  energuidePathway: string;
}

export interface CalculatorLogic {
    totalPoints: number;
    compliance: {
        tier: string;
        status: string;
        description: string;
    };
    costs: {
        prescriptive: number;
        performance: number;
        savings: number;
    };
    getFilteredAirtightnessOptions: () => NBCOption[];
}