import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { Save, FileText, AlertTriangle, Info, Building, Thermometer, Zap, Droplets, Wind, FolderOpen } from 'lucide-react';
import FileManager from '@/components/FileManager';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

interface ProjectSummaryFormProps {
  selections: any;
  uploadedFiles: any[];
  onSave?: () => void;
  editingProjectId?: string;
  autoSave?: boolean;
}

const ProjectSummaryForm = ({ selections, uploadedFiles, onSave, editingProjectId, autoSave = false }: ProjectSummaryFormProps) => {
  const { user } = useAuth();
  const { toast } = useToast();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  
  const getAutoGeneratedProjectName = () => {
    const address = selections?.streetAddress || selections?.city;
    const company = selections?.company;
    const lastName = selections?.lastName;
    
    if (address && company) return `${address} - ${company}`;
    if (address && lastName) return `${address} - ${lastName}`;
    if (company) return `Project - ${company}`;
    if (lastName) return `Project - ${lastName}`;
    
    return 'New NBC Project';
  };
  
  const [projectName, setProjectName] = useState(getAutoGeneratedProjectName());

  useEffect(() => {
    if (autoSave) {
      handleSave();
    }
  }, [autoSave]);

  const getPathwayDisplayName = () => {
    const pathwayMap: { [key: string]: string } = {
      '9365': 'NBC 9.36.5 Performance Path',
      '9362': 'NBC 9.36.2 Prescriptive Path', 
      '9367': 'NBC 9.36.7 Tiered Performance Path',
      '9368': 'NBC 9.36.8 Tiered Prescriptive Path'
    };
    return pathwayMap[selections.compliancePath] || 'NBC 9.36 Pathway';
  };

  const getPendingItems = (selections: any) => {
    const pending: string[] = [];
    const addIfMissing = (field: keyof typeof selections, label: string) => {
      const value = selections[field];
      if (value === null || value === undefined || value === '' || (Array.isArray(value) && value.length === 0)) {
        pending.push(label);
      }
    };

    // Step 1
    addIfMissing('firstName', 'First Name');
    addIfMissing('lastName', 'Last Name');
    addIfMissing('company', 'Company Name');
    addIfMissing('phoneNumber', 'Phone Number');
    addIfMissing('streetAddress', 'Project Street Address');
    addIfMissing('city', 'Project City');
    addIfMissing('province', 'Project Province');
    addIfMissing('postalCode', 'Project Postal Code');
    addIfMissing('buildingType', 'Building Type');
    if (selections.province === 'alberta') addIfMissing('climateZone', 'Climate Zone');

    // Step 2
    addIfMissing('compliancePath', 'Compliance Path');

    // Step 3 (Technical)
    if (selections.compliancePath) {
      if (selections.compliancePath.includes('9365') || selections.compliancePath.includes('9367')) {
        addIfMissing('frontDoorOrientation', 'Front Door Orientation');
        addIfMissing('energuidePathway', 'EnerGuide Pathway Selection');
      }
      addIfMissing('ceilingsAtticRSI', 'Ceilings/Attic Insulation');
      addIfMissing('wallRSI', 'Above Grade Wall Insulation');
      addIfMissing('belowGradeRSI', 'Below Grade Wall Insulation');
      addIfMissing('windowUValue', 'Window U-Value');
      addIfMissing('airtightness', 'Airtightness Level');
      addIfMissing('heatingType', 'Heating Type');
      addIfMissing('waterHeaterType', 'Water Heater Type');
    }
    
    // Step 4 (Documents)
    if (uploadedFiles.length === 0) {
      pending.push('At least one project document (e.g., building plans)');
    }

    return pending;
  };

  const pendingItems = getPendingItems(selections);

  const handleSave = async () => {
    if (!user) {
      toast({ title: "Authentication Required", description: "Please sign in to save.", variant: "destructive" });
      return;
    }
    if (!projectName) {
      toast({ title: "Project Name Required", description: "Please enter a project name.", variant: "destructive" });
      return;
    }

    setLoading(true);
    
    try {
      // Update company info if provided
      if (selections.company || selections.phoneNumber) {
        const { data: company, error: fetchError } = await supabase.from('companies').select('id').eq('user_id', user.id).single();
        if (fetchError && fetchError.code !== 'PGRST116') throw fetchError;

        const companyData = {
          user_id: user.id,
          company_name: selections.company,
          contact_email: user.email,
          phone: selections.phoneNumber,
          address: selections.companyAddress,
        };

        if (company) {
          const { error: updateError } = await supabase.from('companies').update(companyData).eq('id', company.id);
          if (updateError) throw updateError;
        } else {
          const { error: insertError } = await supabase.from('companies').insert(companyData);
          if (insertError) throw insertError;
        }
      }

      const projectData = {
        project_name: projectName,
        building_type: selections.buildingType,
        location: [selections.streetAddress, selections.city, selections.province].filter(Boolean).join(', '),
        street_address: selections.streetAddress,
        unit_number: selections.unitNumber,
        city: selections.city,
        postal_code: selections.postalCode,
        province: selections.province,
        occupancy_class: selections.occupancyClass,
        climate_zone: selections.climateZone,
        selected_pathway: selections.compliancePath,
        
        // Envelope
        attic_rsi: parseFloat(selections.ceilingsAtticRSI) || null,
        wall_rsi: parseFloat(selections.wallRSI) || null,
        below_grade_rsi: parseFloat(selections.belowGradeRSI || selections.foundationWallsRSI) || null,
        floor_rsi: parseFloat(selections.floorsUnheatedRSI || selections.floorsOverUnheatedSpacesRSI) || null,
        window_u_value: parseFloat(selections.windowUValue) || null,
        
        // Mechanical
        heating_system_type: selections.heatingType,
        heating_efficiency: selections.heatingEfficiency,
        secondary_heating_system_type: selections.secondaryHeatingType,
        secondary_heating_efficiency: selections.secondaryHeatingEfficiency,
        cooling_system_type: selections.coolingApplicable === 'yes' ? 'Central AC' : 'None',
        cooling_efficiency: parseFloat(selections.coolingEfficiency) || null,
        water_heating_type: selections.waterHeaterType || selections.waterHeater,
        hrv_erv_type: selections.hasHrv === 'with_hrv' ? 'HRV/ERV' : 'None',
        hrv_erv_efficiency: parseFloat(selections.hrvEfficiency) || null,
        
        // Performance
        airtightness_al: parseFloat(selections.airtightness || selections.customAirtightness) || null,
        building_volume: parseFloat(selections.buildingVolume) || null,
        
        // Status & Files
        compliance_status: 'submitted',
        uploaded_files: uploadedFiles.map(f => ({ name: f.name, size: f.size, type: f.type, path: f.path, url: f.url })),
        mid_construction_blower_door_planned: selections.midConstructionBlowerDoorPlanned,
      };

      let savedProject;
      if (editingProjectId) {
        const { data, error } = await supabase.from('project_summaries').update(projectData).eq('id', editingProjectId).select().single();
        if (error) throw error;
        savedProject = data;
      } else {
        const { data, error } = await supabase.from('project_summaries').insert({ ...projectData, user_id: user.id }).select().single();
        if (error) throw error;
        savedProject = data;
      }

      toast({ title: "Project Submitted", description: "Your project has been successfully submitted for review." });
      onSave?.();
      navigate(`/project/${savedProject.id}`);

    } catch (error: any) {
      console.error('Error saving project:', error);
      toast({ title: "Save Failed", description: error.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const renderField = (label: string, value: any, unit = '') => {
    if (value === null || value === undefined || value === '' || (Array.isArray(value) && value.length === 0)) {
      return null;
    }
    const displayValue = typeof value === 'boolean' ? (value ? 'Yes' : 'No') : value;
    return (
      <div className="flex justify-between items-center text-sm py-2 border-b border-slate-700">
        <span className="text-slate-300">{label}:</span>
        <span className="font-medium text-white">{displayValue} {unit}</span>
      </div>
    );
  };

  return (
    <Card className="w-full max-w-4xl mx-auto bg-slate-800/50 border-slate-700 text-white">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-xl">
          <FileText className="h-5 w-5" />
          {getPathwayDisplayName()}
        </CardTitle>
        <CardDescription className="text-slate-300">Please review all information before submitting.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-2">
          <Label htmlFor="projectName" className="text-slate-200">Project Name *</Label>
          <Input id="projectName" value={projectName} onChange={(e) => setProjectName(e.target.value)} placeholder="Enter project name" className="bg-slate-900/50 border-slate-600" />
        </div>

        <Accordion type="multiple" defaultValue={['item-pending', 'item-1', 'item-2', 'item-3', 'item-4']} className="w-full">
          {pendingItems.length > 0 && (
            <AccordionItem value="item-pending">
              <AccordionTrigger className="text-lg font-semibold text-yellow-400 hover:no-underline">
                <div className="flex items-center gap-2">
                  <AlertTriangle className="h-5 w-5" />
                  Items Pending ({pendingItems.length})
                </div>
              </AccordionTrigger>
              <AccordionContent className="space-y-2 pt-4">
                <p className="text-sm text-slate-300 mb-2">The following required items are missing:</p>
                <ul className="list-disc list-inside space-y-1 text-yellow-300">
                  {pendingItems.map((item, index) => (
                    <li key={index}>{item}</li>
                  ))}
                </ul>
              </AccordionContent>
            </AccordionItem>
          )}

          <AccordionItem value="item-1">
            <AccordionTrigger className="text-lg font-semibold"><Building className="h-5 w-5 mr-2" />Project & Contact Information</AccordionTrigger>
            <AccordionContent className="space-y-2 pt-4">
              {renderField('First Name', selections.firstName)}
              {renderField('Last Name', selections.lastName)}
              {renderField('Company', selections.company)}
              {renderField('Phone Number', selections.phoneNumber)}
              {renderField('Company Address', selections.companyAddress)}
              {renderField('Street Address', selections.streetAddress)}
              {renderField('Unit Number', selections.unitNumber)}
              {renderField('City', selections.city)}
              {renderField('Province', selections.province)}
              {renderField('Postal Code', selections.postalCode)}
              {renderField('Building Type', selections.buildingType)}
              {renderField('Occupancy Class', selections.occupancyClass)}
              {renderField('Climate Zone', selections.climateZone)}
              {renderField('Front Door Orientation', selections.frontDoorOrientation)}
              {renderField('EnerGuide Pathway', selections.energuidePathway)}
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-2">
            <AccordionTrigger className="text-lg font-semibold"><Thermometer className="h-5 w-5 mr-2" />Building Envelope</AccordionTrigger>
            <AccordionContent className="space-y-2 pt-4">
              {renderField('Ceilings/Attic', selections.ceilingsAtticRSI, 'RSI')}
              {renderField('Cathedral/Flat Roof', selections.cathedralFlatRSIValue || selections.cathedralFlatRSI, 'RSI')}
              {renderField('Above Grade Walls', selections.wallRSI, 'RSI')}
              {renderField('Below Grade Walls', selections.belowGradeRSI || selections.foundationWallsRSI, 'RSI')}
              {renderField('Floors over Unheated Spaces', selections.floorsUnheatedRSI || selections.floorsOverUnheatedSpacesRSI, 'RSI')}
              {renderField('Floors over Garages', selections.floorsGarageRSI, 'RSI')}
              {renderField('Heated Floors', selections.heatedFloorsRSI || selections.inFloorHeatRSI, 'RSI')}
              {renderField('Slab on Grade', selections.slabOnGradeRSI || selections.slabOnGradeIntegralFootingRSI, 'RSI')}
              {renderField('Unheated Floor Below Frostline', selections.unheatedFloorBelowFrostRSI)}
              {renderField('Unheated Floor Above Frostline', selections.unheatedFloorAboveFrostRSI, 'RSI')}
              {renderField('Window U-Value', selections.windowUValue, 'W/(m²·K)')}
              {renderField('Skylight U-Value', selections.skylightUValue, 'W/(m²·K)')}
              {renderField('Airtightness', selections.airtightness || selections.customAirtightness, 'ACH50')}
              {renderField('Building Volume', selections.buildingVolume, 'm³')}
              {renderField('Mid-Construction Blower Door Test', selections.midConstructionBlowerDoorPlanned)}
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="item-3">
            <AccordionTrigger className="text-lg font-semibold"><Zap className="h-5 w-5 mr-2" />Mechanical Systems</AccordionTrigger>
            <AccordionContent className="space-y-2 pt-4">
              {renderField('F280 Calculation Completed', selections.hasF280Calculation)}
              {renderField('Heating Type', selections.heatingType)}
              {renderField('Heating Efficiency/Model', selections.heatingEfficiency || selections.heatingMakeModel)}
              {renderField('Indirect Tank (Main)', selections.indirectTank)}
              {renderField('Indirect Tank Size (Main)', selections.indirectTankSize, 'gal')}
              {renderField('Cooling', selections.coolingApplicable)}
              {renderField('Cooling Efficiency/Model', selections.coolingEfficiency || selections.coolingMakeModel)}
              {renderField('Water Heater Type', selections.waterHeaterType || selections.waterHeater)}
              {renderField('Water Heater Model', selections.waterHeaterMakeModel)}
              {renderField('HRV/ERV', selections.hasHrv || selections.hasHrvErv9365)}
              {renderField('HRV/ERV Efficiency/Model', selections.hrvEfficiency || selections.hrvMakeModel)}
              {renderField('Drain Water Heat Recovery', selections.hasDWHR)}
              {renderField('Separate Secondary Heating', selections.hasSecondaryHeating)}
              {renderField('Secondary Heating Type', selections.secondaryHeatingType)}
              {renderField('Secondary Heating Efficiency', selections.secondaryHeatingEfficiency)}
              {renderField('Indirect Tank (Secondary)', selections.secondaryIndirectTank)}
              {renderField('Indirect Tank Size (Secondary)', selections.secondaryIndirectTankSize, 'gal')}
              {renderField('Multiple MURB Heating Systems', selections.hasMurbMultipleHeating)}
              {renderField('MURB Second Heating Type', selections.murbSecondHeatingType)}
              {renderField('MURB Second Heating Efficiency', selections.murbSecondHeatingEfficiency)}
              {renderField('MURB Second Indirect Tank', selections.murbSecondIndirectTank)}
              {renderField('MURB Second Indirect Tank Size', selections.murbSecondIndirectTankSize, 'gal')}
              {renderField('Multiple MURB Water Heaters', selections.hasMurbMultipleWaterHeaters)}
              {renderField('MURB Second Water Heater Type', selections.murbSecondWaterHeaterType)}
              {renderField('MURB Second Water Heater Efficiency', selections.murbSecondWaterHeater)}
            </AccordionContent>
          </AccordionItem>
          
          {selections.interestedCertifications && selections.interestedCertifications.length > 0 && (
            <AccordionItem value="item-optional">
              <AccordionTrigger className="text-lg font-semibold"><Info className="h-5 w-5 mr-2" />Optional Services</AccordionTrigger>
              <AccordionContent className="space-y-2 pt-4">
                {renderField('Interested Certifications', selections.interestedCertifications.join(', '))}
              </AccordionContent>
            </AccordionItem>
          )}

          <AccordionItem value="item-4">
            <AccordionTrigger className="text-lg font-semibold"><FolderOpen className="h-5 w-5 mr-2" />Documents</AccordionTrigger>
            <AccordionContent className="pt-4">
              <FileManager
                files={uploadedFiles}
                onFilesChange={() => {}}
                projectId={editingProjectId || null}
                readOnly={true}
                showUpload={false}
              />
            </AccordionContent>
          </AccordionItem>
        </Accordion>

        <div className="flex justify-start gap-3 pt-6 border-t border-slate-700">
          <Button onClick={handleSave} disabled={loading || !projectName} className="min-w-[120px]">
            {loading ? <div className="animate-spin h-4 w-4 border-2 border-current border-t-transparent rounded-full" /> : <><Save className="h-4 w-4 mr-2" />Submit Project</>}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};

export default ProjectSummaryForm;