// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgiclujcwqihwvuenlni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnaWNsdWpjd3FpaHd2dWVubG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDQ4MTMsImV4cCI6MjA3MTk4MDgxM30.3BLVkh5slLpYchVksAS_98zEkmyRpvFpPdWl1PXhaMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});